/*
    Generated by Atomist on 03 07 2016 
*/
package com.atomist;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = Jim3Application.class)
@WebAppConfiguration
public class Jim3ApplicationTests {

	@Test
	public void contextLoads() {
	}
}
