/*
    Generated by Atomist on 03 07 2016 
*/
package com.atomist;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Jim3Application {

    public static void main(String[] args) {
        SpringApplication.run(Jim3Application.class, args);
    }
}
