/*
    Generated by Atomist on 03 07 2016 
*/
package com.atomist;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for Jim3.
* Don't even think of using XML.
*/
@Configuration
public class Jim3Configuration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
}
